spring:
  application:
    name: hello-service
  webflux:
    base-path: /hello-service/api

server:
  port: 8081
  servlet:
    context-path: /hello-service/api

management:
  tracing:
    sampling:
      probability: 1.0   # sample everything while learning
    propagation:
      type: w3c          # default; could be "w3c,b3" to support both


---
# local configuration
app:
  greet-service:
    base-url: "http://localhost:8082/greet-service/api"